name: the_morning_routine
description: A complete Flutter app that helps users build perfect morning routines.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audioplayers: ^5.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
